version: "3"

services:
  test:
    restart: always
    build: ./
    volumes:
      - ~/jeiger:/root/jeiger
      - ~/.ssh:/root/.ssh
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: zsh
