from cagojeiger/ubuntu:18.04-tensorflow-cpu 
MAINTAINER cagojeiger@naver.com

RUN apt-get update -y

RUN git clone https://github.com/kangheeyong/PROJECT-ML-ENV-setting.git /home/PRJECT-ML-ENV-setting

