from cagojeiger/ubuntu:18.04 
MAINTAINER cagojeiger@naver.com

RUN apt-get update -y
RUN pip3 install tensorflow

RUN git clone https://github.com/kangheeyong/PROJECT-ML-ENV-setting.git /home/PRJECT-ENV-setting

